### ISSUE TITLE
Custom model?

### ISSUE THREAD

**Issue by oravecz** [jgontrum/spacy-api-docker#15]
New to Spacey. Can you describe how one might add their pre-trained model to the docker package?

**Comment by jgontrum** [comment]
Hm, how do you usually integrate your custom packages into spaCy?

My suggestion would be to copy your model file to the project folder, this will automatically add it to the Docker container. By defauly, the API reads the env variable `languages` to load the models with that name (e.g. 'en'). You could change that behaviour here https://github.com/jgontrum/spacy-api-docker/blob/7140779fcf9b79aea14b99d604d286ac09d2c0c9/displacy_service/server.py#L20-L23 by inserting code that loads your custom model.

To also use the frontend, you also have to edit the key `languages` here: https://github.com/jgontrum/spacy-api-docker/blob/7140779fcf9b79aea14b99d604d286ac09d2c0c9/frontend/_data.json#L7
Add an entry like `yourmodelname: yourmodelname` to that object.

**Comment by CartierPierre** [comment]
Is there any way to load a custom model using docker-compose ? With something like this :
```
version: '2'

services:
  spacyapi:
    image: jgontrum/spacyapi:base_v2
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - languages="my_custom_model"
    volumes :
      - my_model_folder:./app/env/lib/python3.6/site-packages/
    restart: always
```
