### ISSUE TITLE
"Schema construction failed" when getting schema on model "en_v2"

### ISSUE THREAD

**Issue by Lotes** [jgontrum/spacy-api-docker#36]
1. Create file `docker-compose.yml`:
```yaml
version: "2"

services:
  spacyapi:
    image: jgontrum/spacyapi:en_v2
    ports:
      - "127.0.0.1:8080:80"
    restart: always
```
2. Execute `docker-compose up`
3. Visit `GET /en/schema`

Result:
```
{
    "title": "Schema construction failed",
    "description": "'NoneType' object is not subscriptable"
}
```
